locations = [
        {"city": "New York", "state": "NY", "coast": "East Coast"},
        {"city": "Los Angeles", "state": "CA", "coast": "West Coast"},
        {"city": "Chicago", "state": "IL", "coast": "Midwest"},
        {"city": "Houston", "state": "TX", "coast": "South Coast"},
        {"city": "Miami", "state": "FL", "coast": "East Coast"},
        {"city": "San Francisco", "state": "CA", "coast": "West Coast"},
        {"city": "Seattle", "state": "WA", "coast": "West Coast"},
        {"city": "Boston", "state": "MA", "coast": "East Coast"},
        {"city": "Dallas", "state": "TX", "coast": "South Coast"},
        {"city": "Washington, D.C.", "state": "DC", "coast": "East Coast"},
        {"city": "Denver", "state": "CO", "coast": "Midwest"},
        {"city": "Philadelphia", "state": "PA", "coast": "East Coast"},
        {"city": "Phoenix", "state": "AZ", "coast": "West Coast"},
        {"city": "Atlanta", "state": "GA", "coast": "South Coast"},
        {"city": "San Diego", "state": "CA", "coast": "West Coast"},
        {"city": "Portland", "state": "OR", "coast": "West Coast"},
        {"city": "Detroit", "state": "MI", "coast": "Midwest"},
        {"city": "Minneapolis", "state": "MN", "coast": "Midwest"},
        {"city": "Charlotte", "state": "NC", "coast": "South Coast"},
        {"city": "Raleigh", "state": "NC", "coast": "South Coast"},
        {"city": "Salt Lake City", "state": "UT", "coast": "West Coast"},
        {"city": "Indianapolis", "state": "IN", "coast": "Midwest"},
        {"city": "St. Louis", "state": "MO", "coast": "Midwest"},
        {"city": "Tampa", "state": "FL", "coast": "East Coast"},
        {"city": "Cleveland", "state": "OH", "coast": "Midwest"},
        {"city": "Orlando", "state": "FL", "coast": "East Coast"},
        {"city": "Austin", "state": "TX", "coast": "South Coast"},
        {"city": "Jacksonville", "state": "FL", "coast": "East Coast"},
        {"city": "Nashville", "state": "TN", "coast": "South Coast"}
     ]